/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trainer;

import java.awt.Button;
import java.sql.Array;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.*;
import static java.util.Calendar.*;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
//import static java.util.Calendar.YEAR;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class addmember1 extends javax.swing.JFrame {

    /**
     * Creates new form addmember1
     */
          Calendar c=new GregorianCalendar();
      int m=c.get(Calendar.MONTH)+1;
      int d2=c.get(Calendar.DAY_OF_MONTH);
      int y=c.get(Calendar.YEAR);
      String p=y+"-"+m+"-"+d2;
        Date d=Date.valueOf(p);
    ButtonGroup bg=new ButtonGroup();
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;  
int j=0;
String f;
public static boolean isNumeric(String str)
{
    for (char c : str.toCharArray())
    {
        if (!Character.isDigit(c)) return false;
    }
    return true;
}

    public addmember1() {
        initComponents();
        GroupButton();
        
        conn=Connection1.Connecterdb();
     //   pop();
         String sql1="select * from Member ";
        
        try
        {
        pst=conn.prepareStatement(sql1);
        rs=pst.executeQuery();
        while(rs.next())
        {
         //   JOptionPane.showMessageDialog(null,"yo");
           j++;
           
        }
        j++;
     
        //JOptionPane.showMessageDialog(null,f);
        }
        catch(Exception e)
        {
            
        }
        f="15RGYM"+String.format("%05d", j);
       
       M_MID.setText(f);
       pop();
    }
void GroupButton()
    {
       // pop();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(jRadioButton3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        M_FN = new javax.swing.JTextField();
        M_MN = new javax.swing.JTextField();
        M_SN = new javax.swing.JTextField();
        M_P = new javax.swing.JTextField();
        M_DOB = new javax.swing.JTextField();
        M_AG = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        M_M = new javax.swing.JTextField();
        M_A = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        M_MID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        M_UA = new javax.swing.JSpinner();
        M_LA = new javax.swing.JSpinner();
        M_WAIST = new javax.swing.JSpinner();
        M_HPS = new javax.swing.JSpinner();
        M_C = new javax.swing.JSpinner();
        M_WHR = new javax.swing.JSpinner();
        M_W = new javax.swing.JSpinner();
        M_T = new javax.swing.JSpinner();
        M_H = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        M_N = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        M_S = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        M_CN = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        M_UARM = new javax.swing.JSpinner();
        M_F = new javax.swing.JSpinner();
        M_CE = new javax.swing.JSpinner();
        M_BMI = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setText("First Name*");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setText("Middel Name*");

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setText("SurName*");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setText("Address*");

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setText("Pin*");

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel6.setText("Mobile No.*");

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel7.setText("Date Of Birth(YYYY-MM-DD)*");

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel8.setText("Age");

        M_FN.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_FNActionPerformed(evt);
            }
        });

        M_MN.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_MN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_MNActionPerformed(evt);
            }
        });

        M_SN.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_P.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_DOB.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_DOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                M_DOBFocusLost(evt);
            }
        });
        M_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_DOBActionPerformed(evt);
            }
        });

        M_AG.setEditable(false);
        M_AG.setBackground(new java.awt.Color(255, 255, 255));
        M_AG.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        jTextField10.setText("+91");

        jRadioButton1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jRadioButton1.setText("Male");

        jRadioButton2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");

        jRadioButton3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jRadioButton3.setText("Other");

        jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel17.setText("Membership*");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel18.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel18.setText("Maritual Status*");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));

        jLabel19.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel19.setText("Gender*");

        M_M.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_A.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Myriad Arabic", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        M_MID.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_MID.setForeground(new java.awt.Color(102, 102, 102));
        M_MID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_MIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel10.setText("Member ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M_MID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(M_DOB, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(M_P, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(M_M, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(M_AG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(M_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(M_MN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(M_SN))
                            .addComponent(M_A))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(M_MID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(M_FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_MN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_SN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(M_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(M_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(M_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(M_AG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jLabel19)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(8, 8, 8)
                        .addComponent(jRadioButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Details", jPanel1);

        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        M_UA.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_LA.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_WAIST.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_HPS.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_C.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_WHR.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_W.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));
        M_W.setToolTipText("0.0");

        M_T.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_H.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));

        jLabel26.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel26.setText("Fore Arm");

        M_N.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(0.1f)));

        jLabel27.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel27.setText("Upper Arm");

        jLabel36.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel36.setText("Chest (Expanded)");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trainer/Actions-ok-icon.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel28.setText("Upper Abdomen");

        jLabel29.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel29.setText("Waist");

        M_S.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel30.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel30.setText("Lower Abdomen");

        M_CN.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));

        jLabel31.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel31.setText("Hips");

        jLabel20.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel20.setText("Height");

        jLabel32.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel32.setText("Thigh");

        jLabel21.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel21.setText("Weight");

        jLabel33.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel33.setText("Calf");

        jLabel22.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel22.setText("Neck");

        jLabel34.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel34.setText("WHR");

        jLabel23.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel23.setText("Shoulder");

        jLabel35.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel35.setText("BMI");

        jLabel25.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel25.setText("Chest (Normal)");

        M_UARM.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_F.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_CE.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        M_BMI.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M_F, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_H, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_N, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_S, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_UARM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_W, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M_UA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_WAIST, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_LA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_HPS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M_C)
                                .addComponent(M_WHR)
                                .addComponent(M_BMI, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(M_T, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(M_W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(M_UA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel30)
                    .addComponent(M_LA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel29)
                    .addComponent(M_WAIST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel31)
                    .addComponent(M_HPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(M_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33))
                    .addComponent(M_CN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(M_UARM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(M_WHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(M_CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(M_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(M_BMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Physical Details", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         //Object s = jComboBox1.getSelectedItem();
         /*String sql="select * from Offer where Name=?";
     try {
      //       f="15RGYM"+j;
     // String h;
        pst=conn.prepareStatement(sql);
        //M_MID.setText(f);
        
        pst.setString(1,jComboBox1.getSelectedItem().toString());
        
           //JOptionPane.showMessageDialog(null,sql);
        rs=pst.executeQuery();
        if(rs.next())
        {
            //JOptionPane.showMessageDialog(null,"whooo");
        
            jTextArea1.setText(rs.getString("Description"));
        }
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
   //             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }*/
    }//GEN-LAST:event_jComboBox1ActionPerformed
public static int getDiffYears(Date first, Date last) {
    Calendar a = GregorianCalendar.getInstance();
    Calendar b = GregorianCalendar.getInstance();
    
    a.setTime(first);
    b.setTime(last);
    int diff = b.get(YEAR) - a.get(YEAR);
    if (a.get(MONTH) > b.get(MONTH) || 
        (a.get(MONTH) == b.get(MONTH) && a.get(DATE) > b.get(DATE))) {
        diff--;
    }
    
    return diff;
}
void pop()
{
    String sql="select Name from Offer Where NewStatus='1' and Expr >= current_date";
              try {
                  pst=conn.prepareStatement(sql);
                   rs=pst.executeQuery();
        //             JOptionPane.showMessageDialog(null,"l0");
      //  List<String> strings = new ArrayList<String>();
               while(rs.next())
                   {
                 // JOptionPane.showMessageDialog(null,rs.getString("Name"));
                 jComboBox1.addItem(rs.getString("Name"));
                   
                   }   
            
              } 
              catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null,"l");
              }
      
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTabbedPane1.setSelectedIndex(1);
       
        
       
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void M_MNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_MNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_MNActionPerformed

    private void M_MIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_MIDActionPerformed
      
    }//GEN-LAST:event_M_MIDActionPerformed

    private void M_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_DOBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_M_DOBActionPerformed

    private void M_DOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_M_DOBFocusLost
        try{
          Date d1=Date.valueOf(M_DOB.getText());
      
     int age=getDiffYears(d1, d);
     if(age<=0)
         throw new Exception();
        M_AG.setText(String.valueOf(age));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Date In Valid Format(YYYY-MM-DD)");
        }
    }//GEN-LAST:event_M_DOBFocusLost
 public static int getDiffYear(Date first, Date last) {
    Calendar a = GregorianCalendar.getInstance();
    Calendar b = GregorianCalendar.getInstance();
    
    a.setTime(first);
    b.setTime(last);
    int diff = b.get(YEAR) - a.get(YEAR);
    if (a.get(MONTH) > b.get(MONTH) || 
        (a.get(MONTH) == b.get(MONTH) && a.get(DATE) > b.get(DATE))) {
        diff--;
    }
    
    return diff;
}   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String o = null;
        String s1="select * from Offer where Name=?";
              try {
                  pst=conn.prepareStatement(s1);
                  pst.setString(1,jComboBox1.getSelectedItem().toString());
                  rs=pst.executeQuery();
                     
                  if(rs.next())
                  {
                     int m=rs.getInt("Duration");
                       o=rs.getString("O_ID");
                  }
              } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"ko");
              }
             
         String sql="insert into Member (M_ID,Name,MiddleName,Surname,MobileNo,DateOfBirth,Age,MaritualStatus,Address,Pin,Gender,StartDate,EndDate,O_ID) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
      try {
          
           if(M_FN.getText().equals("") || M_MN.getText().equals("") || M_SN.getText().equals("") || M_A.getText().equals("") ||M_P.getText().equals("") ||M_M.getText().equals("") || !isNumeric(M_M.getText()) ||M_DOB.getText().equals("") || jTextArea1.getText().equals("") )
       {
           
           throw new Exception();
           
       }
             f="15RGYM"+String.format("%05d",j);
             
        pst=conn.prepareStatement(sql);
        M_MID.setText(f);
        pst.setString(1,M_MID.getText());
        pst.setString(2,M_FN.getText());
        pst.setString(3,M_MN.getText());
        pst.setString(4,M_SN.getText());
        pst.setString(5,M_M.getText());
        pst.setString(6,M_DOB.getText());
        pst.setString(7,M_AG.getText());
        pst.setString(8,jComboBox2.getSelectedItem().toString());
        pst.setString(9,M_A.getText());
        pst.setString(10,M_P.getText());
        if(jRadioButton1.isSelected())
            {
                pst.setString(11,jRadioButton1.getText());
            }
        if(jRadioButton2.isSelected())
            {
                pst.setString(11,jRadioButton2.getText());
            }
        if(jRadioButton3.isSelected())
            {
                pst.setString(11,jRadioButton3.getText());
            }
        
        
           pst.setString(12,d.toString());
           d.setMonth(d.getMonth()+m);
           pst.setString(13, d.toString());
           pst.setString(14,o);
   
           
        pst.execute();
        
        
    }
       catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"Something Wrong With SQL Statement..");
    }
      catch (Exception ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"Please fill valid details....");
    }
    
        
        
        
        
        sql="insert into Physical_Details (date1,Weight,Height,Neck,Shoulder,Chest_n,Chest_e,UpperArm,ForeArm,UpperAbdomen,Waist,LowerAbdomen,Hips,Thigh,Calf,WHR,BMI,M_ID) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
     try {
      //       f="15RGYM"+j;
     // String h;
        pst=conn.prepareStatement(sql);
        //M_MID.setText(f);
        
        pst.setString(1, "Start");
        //JOptionPane.showMessageDialog(null,d);
        
        pst.setFloat(2, (float) M_W.getValue());
        pst.setFloat(3, (float) M_H.getValue());
       //float h= (Float) M_N.getValue();
        //pst.setFloat(2, h);
        pst.setFloat(4, (float)M_N.getValue());
        
        pst.setFloat(5, (float) M_S.getValue());
        
        
        pst.setFloat(6, (float) M_CN.getValue());
        pst.setFloat(7, (float) M_CE.getValue());
        //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
        pst.setFloat(8, (float) M_UARM.getValue());
       // JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
        
        pst.setFloat(9, (float) M_F.getValue());
        pst.setFloat(10, (float) M_UA.getValue());
        pst.setFloat(11, (float) M_WAIST.getValue());
        pst.setFloat(12, (float) M_LA.getValue());
        pst.setFloat(13, (float) M_H.getValue());
        //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
        pst.setFloat(14, (float) M_T.getValue());
     //   pst.setFloat(15, (float) M_UA.getValue());
        pst.setFloat(15, (float) M_C.getValue());
        //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
        pst.setFloat(16, (float) M_WHR.getValue());
        //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
        pst.setFloat(17, (float) M_BMI.getValue());
        pst.setString(18, M_MID.getText());        
           
        pst.execute();
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
   //             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        

    }
     String sop[]={"Second","End"};
     for(int i=0;i<2;i++){
      sql="insert into Physical_Details (M_ID,date1) values (?,?)";
              try {
                  pst=conn.prepareStatement(sql);
                  pst.setString(1, M_MID.getText());
                  pst.setString(2, sop[i]);
                   pst.execute();
       
            
              } 
              catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null,"l");
              }
              finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
   //             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        

    }
     }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void M_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_FNActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
     
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
   
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
  
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
            String sql="select * from Offer where Name=? ";
     try {
      //       f="15RGYM"+j;
     // String h;
        pst=conn.prepareStatement(sql);
        //M_MID.setText(f);
        
       pst.setString(1,jComboBox1.getSelectedItem().toString());
        
         //  JOptionPane.showMessageDialog(null,sql);
        rs=pst.executeQuery();
        if(rs.next())
        {
         //   JOptionPane.showMessageDialog(null,"whooo");
        
            jTextArea1.setText(rs.getString("Description"));
        }
        
    } catch (Exception ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
   //             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmember1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmember1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmember1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmember1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmember1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField M_A;
    private javax.swing.JTextField M_AG;
    private javax.swing.JSpinner M_BMI;
    private javax.swing.JSpinner M_C;
    private javax.swing.JSpinner M_CE;
    private javax.swing.JSpinner M_CN;
    private javax.swing.JTextField M_DOB;
    private javax.swing.JSpinner M_F;
    private javax.swing.JTextField M_FN;
    private javax.swing.JSpinner M_H;
    private javax.swing.JSpinner M_HPS;
    private javax.swing.JSpinner M_LA;
    private javax.swing.JTextField M_M;
    private javax.swing.JTextField M_MID;
    private javax.swing.JTextField M_MN;
    private javax.swing.JSpinner M_N;
    private javax.swing.JTextField M_P;
    private javax.swing.JSpinner M_S;
    private javax.swing.JTextField M_SN;
    private javax.swing.JSpinner M_T;
    private javax.swing.JSpinner M_UA;
    private javax.swing.JSpinner M_UARM;
    private javax.swing.JSpinner M_W;
    private javax.swing.JSpinner M_WAIST;
    private javax.swing.JSpinner M_WHR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    // End of variables declaration//GEN-END:variables
}
