/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trainer;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Scanner;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class EditMemberDetails extends javax.swing.JFrame {

    /**
     * Creates new form EditMemberDetails
     */
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;  
Scanner sc=new Scanner(System.in);
    public EditMemberDetails() {
        initComponents();
        conn=Connection1.Connecterdb();
        //get();
       // pop();
        GroupButton();
    }
  void pop()
{
    String sql="SELECT * FROM Offer INNER JOIN MemOffer ON Offer.O_ID=MemOffer.O_ID where MemOffer.M_ID=? and Expr >= current_date";
              try {
                  pst=conn.prepareStatement(sql);
                  pst.setString(1,M_MID.getText());
                   rs=pst.executeQuery();
                //    JOptionPane.showMessageDialog(null,"l0");
      //  List<String> strings = new ArrayList<String>();
               while(rs.next())
                   {
                 // JOptionPane.showMessageDialog(null,rs.getString("Name"));
                 jComboBox1.addItem(rs.getString("Name"));
                   
                   }   
            
              } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null,"l");
              }
                      finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
      
}
    void popc()
{
    String sql="SELECT Offer.Name,Description FROM Offer INNER JOIN Member ON Offer.O_ID=Member.O_ID where Member.M_ID=? and Expr >= current_date";
              try {
                  pst=conn.prepareStatement(sql);
                 pst.setString(1,M_MID.getText());
                  rs=pst.executeQuery();
                  // JOptionPane.showMessageDialog(null,M_MID.getText());
      //  List<String> strings = new ArrayList<String>();
               if(rs.next())
                   {
                 //JOptionPane.showMessageDialog(null,"Name");
               jTextField1.setText(rs.getString(1));
                 jTextArea2.setText(rs.getString(2));
                   }   
               else
               {
                   jTextField1.setText("");
                 jTextArea2.setText("");
               }
            
              } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null,"error..");
              }
                      finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
      
}
    void GroupButton()
    {
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(jRadioButton3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        M_F = new javax.swing.JTextField();
        M_M = new javax.swing.JTextField();
        M_S = new javax.swing.JTextField();
        M_P = new javax.swing.JTextField();
        M_DOB = new javax.swing.JTextField();
        M_AG = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        M_MS = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        M_MNO = new javax.swing.JTextField();
        M_A = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        M_MID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        M_G = new javax.swing.JTextField();
        M_MST = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setText("Middel Name");

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setText("SurName");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setText("Pin");

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel6.setText("Mobile No.");

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel7.setText("Date Of Birth");

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel8.setText("Age");

        M_F.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_M.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_S.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_P.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_DOB.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        M_AG.setEditable(false);
        M_AG.setBackground(new java.awt.Color(255, 255, 255));
        M_AG.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_AG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_AGActionPerformed(evt);
            }
        });

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        jTextField10.setText("+91");

        jRadioButton1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jRadioButton3.setText("Other");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel17.setText("Membership");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel18.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel18.setText("Maritual Status");

        M_MS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        M_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_MSActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel19.setText("Gender");

        M_MNO.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_MNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_MNOActionPerformed(evt);
            }
        });

        M_A.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Myriad Arabic", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        M_MID.setFont(new java.awt.Font("Myriad Arabic", 0, 18)); // NOI18N
        M_MID.setForeground(new java.awt.Color(102, 102, 102));
        M_MID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                M_MIDFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel10.setText("Member ID");

        M_G.setEditable(false);

        M_MST.setEditable(false);

        jLabel9.setText("Current Membership");

        jTextField1.setText("-----none-----");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel11.setText("Description");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel19)
                                .addGap(21, 21, 21)
                                .addComponent(M_G, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(M_DOB, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(M_P, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8))))
                                        .addComponent(jRadioButton3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(M_MNO, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18)
                                            .addGap(31, 31, 31)
                                            .addComponent(M_MST, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(M_AG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M_MS, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(42, 42, 42))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(74, 74, 74)
                                                    .addComponent(jLabel11)
                                                    .addGap(55, 55, 55)))
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(jRadioButton2)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(M_F, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(M_M, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(M_S))
                                .addComponent(M_A))
                            .addComponent(M_MID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(M_MID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(M_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(M_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(M_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(M_MNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_MST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(M_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(M_AG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M_MS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel9)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(M_G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean isNumeric(String str)
{
    for (char c : str.toCharArray())
    {
        if (!Character.isDigit(c)) return false;
    }
    return true;
}
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void M_MIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_M_MIDFocusLost
         String sql = "select * from Member where M_ID=?";
    try {
        pop();
        popc();
        pst=conn.prepareStatement(sql);
        pst.setString(1,M_MID.getText());
        //pst.setString(2,sc.next()); 
        rs=pst.executeQuery();
        if(rs.next())
        {
            //jRadioButton1.addActionListener((ActionListener) jRadioButton1);
            M_F.setText(rs.getString("Name"));
            M_M.setText(rs.getString("MiddleName"));
            M_S.setText(rs.getString("SurName"));
            M_A.setText(rs.getString("Address"));
            M_P.setText(rs.getString("Pin"));
            M_MNO.setText(rs.getString("MobileNo"));
            M_DOB.setText(rs.getString("DateOfBirth"));
            M_AG.setText(rs.getString("Age"));
            M_MST.setText(rs.getString("MaritualStatus"));
            M_G.setText(rs.getString("Gender"));
           
           }
        else
        {
           JOptionPane.showMessageDialog(null,"NO DATA FOUND.......");
        }
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
      
    }//GEN-LAST:event_M_MIDFocusLost
    
    private void M_MNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_MNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_MNOActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String o = null,o1=null;
        int m=0;
        
        Calendar c=new GregorianCalendar();
          m=c.get(Calendar.MONTH)+1;
      int d2=c.get(Calendar.DAY_OF_MONTH);
      int y=c.get(Calendar.YEAR);
      String p=y+"-"+m+"-"+d2;
       Date m1=Date.valueOf(p);
       Date cur=Date.valueOf(p);
        String s1="select * from Offer where Name=?",s2="select * from Member where M_ID=?";
              try {
                  pst=conn.prepareStatement(s1);
                  pst.setString(1,jComboBox1.getSelectedItem().toString());
                  rs=pst.executeQuery();
                     
                  if(rs.next())
                  {
                      m=rs.getInt("Duration");
                       o=rs.getString("O_ID");
                  }
              } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"ko");
              }
              finally
    {
            try {
                rs.close();
                pst.close();
       //         JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
              try {
                  pst=conn.prepareStatement(s2);
                  pst.setString(1,M_MID.getText());
                  rs=pst.executeQuery();
                     
                  if(rs.next())
                  {
                      String h=rs.getString("EndDate");
                      m1=Date.valueOf(h);
                     // JOptionPane.showMessageDialog(null,h);
                      o1=rs.getString("O_ID");
                  }
              } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"ko");
              }
              finally
    {
            try {
                rs.close();
                pst.close();
       //         JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
        String sql="UPDATE Member SET Name=?, MiddleName=?,SurName=?,MobileNo=?,DateOfBirth=?,Age=?,Address=?,Pin=?,MaritualStatus=?,Gender=?,EndDate=?,O_ID=? WHERE M_ID=? ";
          try {
        pst=conn.prepareStatement(sql);
      //  JOptionPane.showMessageDialog(null,"INCORRECT exception");
        pst.setString(1,M_F.getText());
        pst.setString(2,M_M.getText());
        pst.setString(3,M_S.getText());
        pst.setString(4,M_MNO.getText());
        pst.setString(5,M_DOB.getText());
        pst.setString(6,M_AG.getText());
        pst.setString(7,M_A.getText());
        pst.setString(8,M_P.getText());
        pst.setString(9,M_MST.getText());
        pst.setString(10,M_G.getText());
        
        if(m1.after(cur))
        {
            if(!jTextArea1.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Currently You Cannot Apply For An Offer ");
            pst.setString(11,m1.toString());
            pst.setString(12, o1);
        }
        else
        {
         if(!jTextArea1.getText().equals(""))   
            JOptionPane.showMessageDialog(null,"Congratulations You have successfully apllied for an offer.."); //"+m1+" "+cur);
         m1.setMonth(m1.getMonth()+m);   
         pst.setString(11,m1.toString());
         pst.setString(12,o);
        }
        
        
        pst.setString(13,M_MID.getText()); 
        pst.execute();
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception in edit member details............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
       //         JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }                               
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void M_AGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_AGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_AGActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        M_G.setText("Female");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        M_G.setText("Male");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
M_G.setText("Other");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void M_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_MSActionPerformed
        M_MST.setText((String) M_MS.getSelectedItem());
    }//GEN-LAST:event_M_MSActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         String sql="select * from Offer where Name=? ";
     try {
      //       f="15RGYM"+j;
     // String h;
        pst=conn.prepareStatement(sql);
        //M_MID.setText(f);
        
       pst.setString(1,jComboBox1.getSelectedItem().toString());
        
         //  JOptionPane.showMessageDialog(null,sql);
        rs=pst.executeQuery();
        if(rs.next())
        {
         //   JOptionPane.showMessageDialog(null,"whooo");
        
            jTextArea1.setText(rs.getString("Description"));
        }
        
    } catch (Exception ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"NO FIELD SELECTED");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
   //             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMemberDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField M_A;
    private javax.swing.JTextField M_AG;
    private javax.swing.JTextField M_DOB;
    private javax.swing.JTextField M_F;
    private javax.swing.JTextField M_G;
    private javax.swing.JTextField M_M;
    private javax.swing.JTextField M_MID;
    private javax.swing.JTextField M_MNO;
    private javax.swing.JComboBox<String> M_MS;
    private javax.swing.JTextField M_MST;
    private javax.swing.JTextField M_P;
    private javax.swing.JTextField M_S;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    // End of variables declaration//GEN-END:variables

}
