/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Trainer;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javafx.scene.GroupBuilder;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrator
 */
public class FinalTrainer extends javax.swing.JFrame {
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;  
Scanner sc=new Scanner(System.in);
String op;

    /**
     * Creates new form FinalTrainer
     */
    public FinalTrainer() {
        initComponents();
        GroupButton();
        conn=Connection1.Connecterdb();
        setvisible();
          jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));
          jButton6.setVisible(false);
    }
    void setvisible()
    {
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jTextField3.setVisible(false);
        jButton5.setVisible(false);
    }
   void GroupButton()
    {
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(N_M);
    }     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        N_M = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setText("Add Visitor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.lightGray);
        jButton2.setText("Add Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.lightGray);
        jButton3.setText("Edit Member Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.lightGray);
        jButton4.setText("Progress Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jButton9.setText("Fill Exercise");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trainer/download.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Member Details", jPanel3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel7.setText("Active Members-:");

        jLabel8.setText("InActive Members");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fees Details", jPanel5);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Offer Name (Heading)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Offer ID");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Criteria");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--none--", "Visitor", "Member" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("All");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Selected");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Member ID", "Name", "Surname", "Age", "Date Of Birth", "Gender"
            }
        ));
        jTable1.setEditingColumn(0);
        jTable1.setEditingRow(0);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Create");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        N_M.setText("New Members");
        N_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_MMouseClicked(evt);
            }
        });
        N_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_MActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(N_M))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(N_M))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jButton8.setText("Create Offer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Duration(Month)");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Expiry Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(513, 513, 513))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jButton8))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Offer/Events", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder());
       AddVisitor av=new AddVisitor();
       av.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
av.pack();
av.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                                                 
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
      addmember1 am=new addmember1();
      am.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
am.pack();
am.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                                 
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        EditMemberDetails em=new EditMemberDetails();
        em.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
em.pack();
em.setVisible(true);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                                 
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        ProgressReport pr=new ProgressReport();
        pr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
pr.pack();
pr.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       
        if(jComboBox1.getSelectedItem().equals("--none--"))
        {
            
        }
        else
        {
            if(jComboBox1.getSelectedItem().equals("Visitor"))
            {
                
                jComboBox2.setVisible(true);
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "Name", "SurName", "DateOfBirth" }));
            }
            else if(jComboBox1.getSelectedItem().equals("Member"))
            {
                
                jComboBox2.setVisible(true);
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "M_ID", "Name","SurName", "DateOfBirth", "Age","Gender" }));    
            }
        }
        
        jComboBox1.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jRadioButton1.isSelected())
        {
            String sql;
            if(jComboBox1.getSelectedItem().equals("Visitor")){
             sql="select Name,SurName,MobileNo,DateOfBirth from "+jComboBox1.getSelectedItem();
            }
            else
            {
                sql="select * from "+jComboBox1.getSelectedItem();
            }
          //  JOptionPane.showMessageDialog(null,sql);
             try {
        pst=conn.prepareStatement(sql);
      
       rs=pst.executeQuery();
            do
        {
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));    
            //JOptionPane.showMessageDialog(null,"CORRECT............................................................");
        
        
        }while(rs.next());
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }                               
            jComboBox1.setVisible(true);
            jComboBox2.setVisible(false);
            jComboBox3.setVisible(false);
            jTextField3.setVisible(false);
            jButton5.setVisible(false);
            
        }
        else
        {
            if(jComboBox1.getSelectedItem().equals("Visitor"))
            {
                
                jComboBox2.setVisible(true);
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "Name", "SurName", "DateOfBirth" }));
            }
            else if(jComboBox1.getSelectedItem().equals("Member"))
            {
                
                jComboBox2.setVisible(true);
                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "M_ID", "Name","SurName", "DateOfBirth", "Age","Gender" }));    
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       
        if(jComboBox1.getSelectedItem().equals("Visitor"))
        {
            if(jRadioButton1.isSelected())
            {
                jComboBox1.setVisible(true);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jTextField3.setVisible(false);
                jButton5.setVisible(false);
            }
            if(jComboBox2.getSelectedItem().equals("Name")||jComboBox2.getSelectedItem().equals("SurName")||jComboBox2.getSelectedItem().equals("DateOfBirth"))
            {
                if(jRadioButton1.isSelected())
                {
                    jComboBox1.setVisible(true);
                    jComboBox2.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField3.setVisible(false);
                    jButton5.setVisible(false);
                }
                jButton5.setVisible(true);
                jTextField3.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "=" }));
            }
            else if(jComboBox2.getSelectedItem().equals("Age"))
            {
                if(jRadioButton1.isSelected())
                {
                    jComboBox1.setVisible(true);
                    jComboBox2.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField3.setVisible(false);
                    jButton5.setVisible(false);
                }
                jButton5.setVisible(true);
                jTextField3.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "=","<",">"}));
            }
        }
        else if(jComboBox1.getSelectedItem().equals("Member"))
        {
            if(jRadioButton1.isSelected())
            {
                jComboBox1.setVisible(true);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jTextField3.setVisible(false);
                jButton5.setVisible(false);
            }
            if(jComboBox2.getSelectedItem().equals("Name")||jComboBox2.getSelectedItem().equals("SurName")||jComboBox2.getSelectedItem().equals("DateOfBirth")||jComboBox2.getSelectedItem().equals("Gender"))
            {
                if(jRadioButton1.isSelected())
                {
                    jComboBox1.setVisible(true);
                    jComboBox2.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField3.setVisible(false);
                    jButton5.setVisible(false);
                }
                jButton5.setVisible(true);
                jTextField3.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "=" }));
            }
            else if(jComboBox2.getSelectedItem().equals("Age")||jComboBox2.getSelectedItem().equals("M_ID"))
            {
                if(jRadioButton1.isSelected())
                {
                    jComboBox1.setVisible(true);
                    jComboBox2.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField3.setVisible(false);
                    jButton5.setVisible(false);
                }
                jButton5.setVisible(true);
                jTextField3.setVisible(true);
                jComboBox3.setVisible(true);
                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--none--", "=","<",">"}));
            }
        }
        if(jRadioButton1.isSelected())
        {
            if(jRadioButton1.isSelected())
            {
                jComboBox1.setVisible(true);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(false);
                jTextField3.setVisible(false);
                jButton5.setVisible(false);
            }
            jComboBox1.setVisible(true);
            jComboBox2.setVisible(false);
            jComboBox3.setVisible(false);
            jTextField3.setVisible(false);
            jButton5.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    jButton5.setVisible(true);
    jButton6.setVisible(false);
    jComboBox1.setVisible(true);
    jComboBox2.setVisible(false);
    jComboBox3.setVisible(false);
    jTextField3.setVisible(false);
    jButton5.setVisible(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        String sql="select * from "+jComboBox1.getSelectedItem()+" where "+jComboBox2.getSelectedItem()+jComboBox3.getSelectedItem()+"'"+jTextField3.getText()+"'";
try {
   // JOptionPane.showMessageDialog(null,sql);
    
        pst=conn.prepareStatement(sql);
      
       rs=pst.executeQuery();
        do
        {
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));    
            //JOptionPane.showMessageDialog(null,"CORRECT............................................................");
        
        
        }while(rs.next());
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }        

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
      //  if(jComboBox3.getSelectedItem().equals(""))
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) jTable1.getModel();
        int k=jTable1.getSelectedRow();
        modelTable.removeRow(k);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jButton6.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int count=jTable1.getRowCount();
      
        
        
        if(jComboBox1.getSelectedItem().equals("Member") && !jTextField2.getText().equals("")){
        for(int i=0;i<count;i++)
        {
               String sql="insert into MemOffer (M_ID,O_ID) values (?,?)";
        try {
            pst=conn.prepareStatement(sql);
           String r=(jTable1.getModel().getValueAt(i,0)).toString();
           pst.setString(1,r);
           pst.setString(2,jTextField2.getText());
           pst.execute();
            }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
           finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
        }
        
        }
        else if(!jTextField2.getText().equals("") && jComboBox1.getSelectedItem().equals("Visitor"))
        {
            for(int i=0;i<count;i++)
        {
               String sql="update  Visitor set O_ID=? where Name=? and SurName=? ";
        try {
            pst=conn.prepareStatement(sql);
           String r=(jTable1.getModel().getValueAt(i,0)).toString();
           JOptionPane.showMessageDialog(null,r);
           String r1=(jTable1.getModel().getValueAt(i,1)).toString();
           JOptionPane.showMessageDialog(null,r1);
           //String r2=(jTable1.getModel().getValueAt(i,3)).toString();
           //JOptionPane.showMessageDialog(null,r2);
           pst.setString(1,jTextField2.getText());
           pst.setString(2,r);
           //pst.setString(3,r1);
           pst.setString(3,r1);
           
           pst.execute();
            }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
           finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
        }
            
        }
        else if(N_M.isSelected()&& !jTextField2.getText().equals(""))
        {
            String sql="update  Offer set NewStatus=? where O_ID=?";
            try {
            pst=conn.prepareStatement(sql);
           //String r=jTextField2.getText();
          // JOptionPane.showMessageDialog(null,r);
           String r1="1";
           JOptionPane.showMessageDialog(null,r1);
           //String r2=(jTable1.getModel().getValueAt(i,3)).toString();
           //JOptionPane.showMessageDialog(null,r2);
           pst.setString(2,jTextField2.getText());
           pst.setString(1,r1);
           //pst.setString(3,r1);
          // pst.setString(3,r1);
           
           pst.execute();
            }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
               finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Fillup All Fields..");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      String sql1="insert into Offer (Name,Description,O_ID,Duration,Expr) values (?,?,?,?,?)";
        try {
            pst=conn.prepareStatement(sql1);
           pst.setString(1,jTextField4.getText());
           pst.setString(2,jTextArea1.getText());
           pst.setString(3,jTextField2.getText());
           pst.setString(4,jTextField1.getText());
           pst.setString(5,jTextField5.getText());
           pst.execute();
            }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
           finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"INCORRECT exception.......");
            }
       
    }
    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void N_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_MActionPerformed
      
    }//GEN-LAST:event_N_MActionPerformed

    private void N_MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_MMouseClicked
  jButton5.setVisible(false);
    jButton6.setVisible(false);
    jComboBox1.setVisible(false);
    jComboBox2.setVisible(false);
    jComboBox3.setVisible(false);
    jTextField3.setVisible(false);
    jButton5.setVisible(false);
    //jTable1.setVisible(false);
//    JOptionPane.showMessageDialog(null,"fhd");
        String sql="select * from Member where Name="+"'"+"-1"+"'";
try {
  //  JOptionPane.showMessageDialog(null,sql);
    
        pst=conn.prepareStatement(sql);
      
       rs=pst.executeQuery();
        do
        {
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));    
            //JOptionPane.showMessageDialog(null,"CORRECT............................................................");
        
        
        }while(rs.next());
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"INCORRECT exception............................................................");
    }
    finally
    {
            try {
                rs.close();
                pst.close();
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }        


    
    }//GEN-LAST:event_N_MMouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        String sql="select M_ID,Name,MiddleName,SurName from Member where Active='1'";
        try {
   // JOptionPane.showMessageDialog(null,sql);
    
        pst=conn.prepareStatement(sql);
      
       rs=pst.executeQuery();
        do
        {
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));    
            //JOptionPane.showMessageDialog(null,"CORRECT............................................................");
        
        
        }while(rs.next());
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"In  "+ex);
    }
    
             sql="select M_ID,Name,MiddleName,SurName from Member where Active='0'";
        try {
   // JOptionPane.showMessageDialog(null,sql);
    
        pst=conn.prepareStatement(sql);
      
       rs=pst.executeQuery();
        do
        {
        jTable3.setModel(DbUtils.resultSetToTableModel(rs));    
            //JOptionPane.showMessageDialog(null,"CORRECT............................................................");
        
        
        }while(rs.next());
        
    } catch (SQLException ex) {
        //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null,"In "+ex);
    } 
           finally
    {
            try {
                rs.close();
                pst.close();
     //           JOptionPane.showMessageDialog(null,"Connection lost..");
                
            } catch (SQLException ex) {
      //          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null,"IN  "+ex);
            }
       
    }
    
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
FillExe f=new FillExe();

f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
f.pack();
f.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton N_M;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
 
}
