package Trainer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class ProgressReport extends javax.swing.JFrame {

    /**
     * Creates new form ProgressReport
     */
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;  

    public ProgressReport() {
        initComponents();
        conn=Connection1.Connecterdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        M_W7 = new javax.swing.JSpinner();
        jLabel133 = new javax.swing.JLabel();
        M_H7 = new javax.swing.JSpinner();
        jLabel134 = new javax.swing.JLabel();
        M_N7 = new javax.swing.JSpinner();
        jLabel135 = new javax.swing.JLabel();
        M_S7 = new javax.swing.JSpinner();
        jLabel136 = new javax.swing.JLabel();
        M_CN7 = new javax.swing.JSpinner();
        jLabel137 = new javax.swing.JLabel();
        M_UARM7 = new javax.swing.JSpinner();
        jLabel138 = new javax.swing.JLabel();
        M_CE7 = new javax.swing.JSpinner();
        jLabel139 = new javax.swing.JLabel();
        M_F7 = new javax.swing.JSpinner();
        jLabel140 = new javax.swing.JLabel();
        M_UA7 = new javax.swing.JSpinner();
        jLabel141 = new javax.swing.JLabel();
        M_LA7 = new javax.swing.JSpinner();
        jLabel142 = new javax.swing.JLabel();
        M_WAIST7 = new javax.swing.JSpinner();
        jLabel143 = new javax.swing.JLabel();
        M_HPS7 = new javax.swing.JSpinner();
        jLabel144 = new javax.swing.JLabel();
        M_C7 = new javax.swing.JSpinner();
        jLabel145 = new javax.swing.JLabel();
        M_WHR7 = new javax.swing.JSpinner();
        jLabel146 = new javax.swing.JLabel();
        M_T7 = new javax.swing.JSpinner();
        jLabel147 = new javax.swing.JLabel();
        M_BMI7 = new javax.swing.JSpinner();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel132.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel132.setText("Weight");

        M_W7.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));
        M_W7.setToolTipText("0.0");

        jLabel133.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel133.setText("Height");

        M_H7.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));

        jLabel134.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel134.setText("Neck");

        M_N7.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(0.1f)));

        jLabel135.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel135.setText("Shoulder");

        M_S7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel136.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel136.setText("Chest (Normal)");

        M_CN7.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(250.0f), Float.valueOf(1.0f)));

        jLabel137.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel137.setText("Upper Arm");

        M_UARM7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel138.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel138.setText("Chest (Expanded)");

        M_CE7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel139.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel139.setText("Fore Arm");

        M_F7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel140.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel140.setText("Upper Abdomen");

        M_UA7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel141.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel141.setText("Lower Abdomen");

        M_LA7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel142.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel142.setText("Waist");

        M_WAIST7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel143.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel143.setText("Hips");

        M_HPS7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel144.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel144.setText("Calf");

        M_C7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel145.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel145.setText("WHR");

        M_WHR7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel146.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel146.setText("Thigh");

        M_T7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel147.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel147.setText("BMI");

        M_BMI7.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trainer/Actions-ok-icon.png"))); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("MemberID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel136, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel138)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel134, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel133, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel137, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M_F7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_H7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_N7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_S7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_UARM7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_W7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_CE7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_CN7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel140, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel142, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel141, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M_UA7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_WAIST7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_LA7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_HPS7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel145, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel147, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M_C7)
                                .addComponent(M_WHR7)
                                .addComponent(M_BMI7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel146, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(M_T7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel132)
                        .addComponent(M_W7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel140)
                        .addComponent(M_UA7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel133)
                    .addComponent(jLabel141)
                    .addComponent(M_LA7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_H7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel134)
                    .addComponent(jLabel142)
                    .addComponent(M_WAIST7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_N7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel135)
                    .addComponent(jLabel143)
                    .addComponent(M_HPS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_S7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel136)
                        .addComponent(M_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel144))
                    .addComponent(M_CN7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel137)
                    .addComponent(M_UARM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel145)
                    .addComponent(M_WHR7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel138)
                    .addComponent(M_CE7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_T7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel146))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel139)
                    .addComponent(M_F7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel147)
                    .addComponent(M_BMI7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

String        sql="update Physical_Details set Weight=?,Height=?,Neck=?,Shoulder=?,Chest_n=?,Chest_e=?,UpperArm=?,ForeArm=?,UpperAbdomen=?,Waist=?,LowerAbdomen=?,Hips=?,Thigh=?,Calf=?,WHR=?,BMI=?  where  M_ID=? and date1='End'";
        try {
            //       f="15RGYM"+j;
            // String h;
            pst=conn.prepareStatement(sql);
            //M_MID.setText(f);

            
            

            pst.setFloat(1, (float) M_W7.getValue());
            //JOptionPane.showMessageDialog(null,"d");
            pst.setFloat(2, (float) M_H7.getValue());
            //float h= (Float) M_N.getValue();
            //pst.setFloat(2, h);
            pst.setFloat(3, (float)M_N7.getValue());

            pst.setFloat(4, (float) M_S7.getValue());

            pst.setFloat(5, (float) M_CN7.getValue());
            pst.setFloat(6, (float) M_CE7.getValue());
            //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
            pst.setFloat(7, (float) M_UARM7.getValue());
           

            pst.setFloat(8, (float) M_F7.getValue());
            pst.setFloat(9, (float) M_UA7.getValue());
            pst.setFloat(10, (float) M_WAIST7.getValue());
            pst.setFloat(11, (float) M_LA7.getValue());
            pst.setFloat(12, (float) M_H7.getValue());
            //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
            pst.setFloat(13, (float) M_T7.getValue());
            //   pst.setFloat(15, (float) M_UA.getValue());
            pst.setFloat(14, (float) M_C7.getValue());
            //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
            pst.setFloat(15, (float) M_WHR7.getValue());
          //  JOptionPane.showMessageDialog(null,"bno");
            //JOptionPane.showMessageDialog(null,(Float)M_N.getValue());
            pst.setFloat(16, (float) M_BMI7.getValue());
            //JOptionPane.showMessageDialog(null,"YO");
           // JOptionPane.showMessageDialog(null,"bno");
            if(jTextField1.getText().contains(""))
             //   System.out.println("");  
            pst.setString(17, jTextField1.getText());
            else
                throw new SQLException();
            

            pst.execute();

        } catch (Exception ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Icorrect Input...");
        }
        finally
        {
            try {
               // rs.close();
                pst.close();

            } catch (SQLException ex) {
                //             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner M_BMI;
    private javax.swing.JSpinner M_BMI1;
    private javax.swing.JSpinner M_BMI2;
    private javax.swing.JSpinner M_BMI3;
    private javax.swing.JSpinner M_BMI4;
    private javax.swing.JSpinner M_BMI5;
    private javax.swing.JSpinner M_BMI6;
    private javax.swing.JSpinner M_BMI7;
    private javax.swing.JSpinner M_C;
    private javax.swing.JSpinner M_C1;
    private javax.swing.JSpinner M_C2;
    private javax.swing.JSpinner M_C3;
    private javax.swing.JSpinner M_C4;
    private javax.swing.JSpinner M_C5;
    private javax.swing.JSpinner M_C6;
    private javax.swing.JSpinner M_C7;
    private javax.swing.JSpinner M_CE;
    private javax.swing.JSpinner M_CE1;
    private javax.swing.JSpinner M_CE2;
    private javax.swing.JSpinner M_CE3;
    private javax.swing.JSpinner M_CE4;
    private javax.swing.JSpinner M_CE5;
    private javax.swing.JSpinner M_CE6;
    private javax.swing.JSpinner M_CE7;
    private javax.swing.JSpinner M_CN;
    private javax.swing.JSpinner M_CN1;
    private javax.swing.JSpinner M_CN2;
    private javax.swing.JSpinner M_CN3;
    private javax.swing.JSpinner M_CN4;
    private javax.swing.JSpinner M_CN5;
    private javax.swing.JSpinner M_CN6;
    private javax.swing.JSpinner M_CN7;
    private javax.swing.JSpinner M_F;
    private javax.swing.JSpinner M_F1;
    private javax.swing.JSpinner M_F2;
    private javax.swing.JSpinner M_F3;
    private javax.swing.JSpinner M_F4;
    private javax.swing.JSpinner M_F5;
    private javax.swing.JSpinner M_F6;
    private javax.swing.JSpinner M_F7;
    private javax.swing.JSpinner M_H;
    private javax.swing.JSpinner M_H1;
    private javax.swing.JSpinner M_H2;
    private javax.swing.JSpinner M_H3;
    private javax.swing.JSpinner M_H4;
    private javax.swing.JSpinner M_H5;
    private javax.swing.JSpinner M_H6;
    private javax.swing.JSpinner M_H7;
    private javax.swing.JSpinner M_HPS;
    private javax.swing.JSpinner M_HPS1;
    private javax.swing.JSpinner M_HPS2;
    private javax.swing.JSpinner M_HPS3;
    private javax.swing.JSpinner M_HPS4;
    private javax.swing.JSpinner M_HPS5;
    private javax.swing.JSpinner M_HPS6;
    private javax.swing.JSpinner M_HPS7;
    private javax.swing.JSpinner M_LA;
    private javax.swing.JSpinner M_LA1;
    private javax.swing.JSpinner M_LA2;
    private javax.swing.JSpinner M_LA3;
    private javax.swing.JSpinner M_LA4;
    private javax.swing.JSpinner M_LA5;
    private javax.swing.JSpinner M_LA6;
    private javax.swing.JSpinner M_LA7;
    private javax.swing.JSpinner M_N;
    private javax.swing.JSpinner M_N1;
    private javax.swing.JSpinner M_N2;
    private javax.swing.JSpinner M_N3;
    private javax.swing.JSpinner M_N4;
    private javax.swing.JSpinner M_N5;
    private javax.swing.JSpinner M_N6;
    private javax.swing.JSpinner M_N7;
    private javax.swing.JSpinner M_S;
    private javax.swing.JSpinner M_S1;
    private javax.swing.JSpinner M_S2;
    private javax.swing.JSpinner M_S3;
    private javax.swing.JSpinner M_S4;
    private javax.swing.JSpinner M_S5;
    private javax.swing.JSpinner M_S6;
    private javax.swing.JSpinner M_S7;
    private javax.swing.JSpinner M_T;
    private javax.swing.JSpinner M_T1;
    private javax.swing.JSpinner M_T2;
    private javax.swing.JSpinner M_T3;
    private javax.swing.JSpinner M_T4;
    private javax.swing.JSpinner M_T5;
    private javax.swing.JSpinner M_T6;
    private javax.swing.JSpinner M_T7;
    private javax.swing.JSpinner M_UA;
    private javax.swing.JSpinner M_UA1;
    private javax.swing.JSpinner M_UA2;
    private javax.swing.JSpinner M_UA3;
    private javax.swing.JSpinner M_UA4;
    private javax.swing.JSpinner M_UA5;
    private javax.swing.JSpinner M_UA6;
    private javax.swing.JSpinner M_UA7;
    private javax.swing.JSpinner M_UARM;
    private javax.swing.JSpinner M_UARM1;
    private javax.swing.JSpinner M_UARM2;
    private javax.swing.JSpinner M_UARM3;
    private javax.swing.JSpinner M_UARM4;
    private javax.swing.JSpinner M_UARM5;
    private javax.swing.JSpinner M_UARM6;
    private javax.swing.JSpinner M_UARM7;
    private javax.swing.JSpinner M_W;
    private javax.swing.JSpinner M_W1;
    private javax.swing.JSpinner M_W2;
    private javax.swing.JSpinner M_W3;
    private javax.swing.JSpinner M_W4;
    private javax.swing.JSpinner M_W5;
    private javax.swing.JSpinner M_W6;
    private javax.swing.JSpinner M_W7;
    private javax.swing.JSpinner M_WAIST;
    private javax.swing.JSpinner M_WAIST1;
    private javax.swing.JSpinner M_WAIST2;
    private javax.swing.JSpinner M_WAIST3;
    private javax.swing.JSpinner M_WAIST4;
    private javax.swing.JSpinner M_WAIST5;
    private javax.swing.JSpinner M_WAIST6;
    private javax.swing.JSpinner M_WAIST7;
    private javax.swing.JSpinner M_WHR;
    private javax.swing.JSpinner M_WHR1;
    private javax.swing.JSpinner M_WHR2;
    private javax.swing.JSpinner M_WHR3;
    private javax.swing.JSpinner M_WHR4;
    private javax.swing.JSpinner M_WHR5;
    private javax.swing.JSpinner M_WHR6;
    private javax.swing.JSpinner M_WHR7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
